version: 2

defaults: &defaults
  working_directory: ~/signalr-no-jquery
  docker:
    - image: circleci/node:8.9.1
jobs:
  deploy:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - restore_cache:
            keys:
            - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run: npm install
        - run: npm update
        - run: npm prune
        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-
        - run: npm run build
        - run:
            name: Versioning
            command: npm version 1.0.$CIRCLE_BUILD_NUM --no-git-tag-version
        - run:
            name: Version
            command: npm version
        - run:
            name: Publish package
            command: npm publish --access public
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /^master/
